In [34]:
import pandas as pd
import os

In [35]:
pwd = os.getcwd()

In [36]:
dataset = pd.read_excel(pwd + "\\Data - Copy of Source.xlsx", sheet_name="Edited_Data")
dataset

,ID,StartDate,EndDate,Gender - Response,Age - Response,Household Income - Response,Education - Response,Location (Census Region) - Response,Which of the following best describes your current relationship status? - Response,"How long have you been in your current relationship? If you are not currently in a relationship, please answer according to your last relationship. - Response",...,What are the reasons that you sleep in separate beds? Please select all that apply. - Do not want to share the covers,What are the reasons that you sleep in separate beds? Please select all that apply. - One of us needs to sleep with a child,What are the reasons that you sleep in separate beds? Please select all that apply. - Night working/very different sleeping times,What are the reasons that you sleep in separate beds? Please select all that apply. - Other (please specify),When was the first time you slept in separate beds? - Response,"To what extent do you agree with the following statement: ""sleeping in separate beds helps us to stay together."" - Response","To what extent do you agree with the following statement: ""we sleep better when we sleep in separate beds."" - Response","To what extent do you agree with the following statement:ë_""our sex life has improved as a result of sleeping in separate beds.""ë_ - Response",Which of the following best describes your current occupation? - Response,Which of the following best describes your current occupation? - Other (please specify)
0,1,2014-07-10 18:37:00,2014-07-10 18:39:00,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,"Single, but cohabiting with a significant other",1-5 years,...,NaN,NaN,NaN,Other (please specify),Within the first 1-5 years of our relationship,Strongly disagree,Somewhat agree,Strongly disagree,Other (please specify),Student
1,2,2014-07-10 15:54:00,2014-07-10 15:56:00,Male,18-29,NaN,Bachelor degree,South Atlantic,"Single, but cohabiting with a significant other",1-5 years,...,Do not want to share the covers,NaN,NaN,NaN,Immediately/ We've always slept in separate beds,Somewhat agree,Strongly agree,Strongly disagree,Healthcare Support Occupations,NaN
2,3,2014-07-10 15:44:00,2014-07-10 15:49:00,Male,18-29,"$150,000+",Graduate degree,South Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Legal Occupations,NaN
3,4,2014-07-10 13:47:00,2014-07-10 13:47:00,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Life, Physical, and Social Science Occupations",NaN
4,5,2014-07-10 13:13:00,2014-07-10 13:14:00,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,1089,2014-07-09 17:46:00,2014-07-09 17:49:00,Female,30-44,NaN,Bachelor degree,South Atlantic,Married,Less than 1 year,...,NaN,NaN,Night working/very different sleeping times,NaN,Within the first 1-5 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,"Arts, Design, Entertainment, Sports, and Media...",NaN
1089,1090,2014-07-09 17:46:00,2014-07-09 17:49:00,Male,> 60,NaN,High school degree,East North Central,Married,More than 20 years,...,NaN,NaN,NaN,NaN,After 20 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Other (please specify),retired
1090,1091,2014-07-09 17:46:00,2014-07-09 17:47:00,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Management Occupations,NaN
1091,1092,2014-07-09 17:45:00,2014-07-09 17:46:00,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,Separated,16-20 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Arts, Design, Entertainment, Sports, and Media...",NaN
1092,1093,2014-07-09 17:45:00,2014-07-09 17:46:00,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,Married,More than 20 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,NaN

In [37]:
dataset_modified = dataset.copy()
dataset_modified

,ID,StartDate,EndDate,Gender - Response,Age - Response,Household Income - Response,Education - Response,Location (Census Region) - Response,Which of the following best describes your current relationship status? - Response,"How long have you been in your current relationship? If you are not currently in a relationship, please answer according to your last relationship. - Response",...,What are the reasons that you sleep in separate beds? Please select all that apply. - Do not want to share the covers,What are the reasons that you sleep in separate beds? Please select all that apply. - One of us needs to sleep with a child,What are the reasons that you sleep in separate beds? Please select all that apply. - Night working/very different sleeping times,What are the reasons that you sleep in separate beds? Please select all that apply. - Other (please specify),When was the first time you slept in separate beds? - Response,"To what extent do you agree with the following statement: ""sleeping in separate beds helps us to stay together."" - Response","To what extent do you agree with the following statement: ""we sleep better when we sleep in separate beds."" - Response","To what extent do you agree with the following statement:ë_""our sex life has improved as a result of sleeping in separate beds.""ë_ - Response",Which of the following best describes your current occupation? - Response,Which of the following best describes your current occupation? - Other (please specify)
0,1,2014-07-10 18:37:00,2014-07-10 18:39:00,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,"Single, but cohabiting with a significant other",1-5 years,...,NaN,NaN,NaN,Other (please specify),Within the first 1-5 years of our relationship,Strongly disagree,Somewhat agree,Strongly disagree,Other (please specify),Student
1,2,2014-07-10 15:54:00,2014-07-10 15:56:00,Male,18-29,NaN,Bachelor degree,South Atlantic,"Single, but cohabiting with a significant other",1-5 years,...,Do not want to share the covers,NaN,NaN,NaN,Immediately/ We've always slept in separate beds,Somewhat agree,Strongly agree,Strongly disagree,Healthcare Support Occupations,NaN
2,3,2014-07-10 15:44:00,2014-07-10 15:49:00,Male,18-29,"$150,000+",Graduate degree,South Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Legal Occupations,NaN
3,4,2014-07-10 13:47:00,2014-07-10 13:47:00,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Life, Physical, and Social Science Occupations",NaN
4,5,2014-07-10 13:13:00,2014-07-10 13:14:00,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,1089,2014-07-09 17:46:00,2014-07-09 17:49:00,Female,30-44,NaN,Bachelor degree,South Atlantic,Married,Less than 1 year,...,NaN,NaN,Night working/very different sleeping times,NaN,Within the first 1-5 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,"Arts, Design, Entertainment, Sports, and Media...",NaN
1089,1090,2014-07-09 17:46:00,2014-07-09 17:49:00,Male,> 60,NaN,High school degree,East North Central,Married,More than 20 years,...,NaN,NaN,NaN,NaN,After 20 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Other (please specify),retired
1090,1091,2014-07-09 17:46:00,2014-07-09 17:47:00,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,Married,1-5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Management Occupations,NaN
1091,1092,2014-07-09 17:45:00,2014-07-09 17:46:00,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,Separated,16-20 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Arts, Design, Entertainment, Sports, and Media...",NaN
1092,1093,2014-07-09 17:45:00,2014-07-09 17:46:00,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,Married,More than 20 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,NaN

In [38]:
dataset_modified.columns

Index(['ID', 'StartDate', 'EndDate', 'Gender - Response', 'Age - Response',
       'Household Income - Response', 'Education - Response',
       'Location (Census Region) - Response',
       'Which of the following best describes your current relationship status? - Response',
       'How long have you been in your current relationship? If you are not currently in a relationship, please answer according to your last relationship. - Response',
       'When both you and your partner are at home, how often do you sleep in separate beds? - Response',
       'When you're not sleeping in the same bed as your partner, where do you typically sleep? - Response',
       'When you're not sleeping in the same bed as your partner, where do you typically sleep? - Other (please specify)',
       'When you're not sleeping in the same bed, where does your partner typically sleep? - Response',
       'When you're not sleeping in the same bed, where does your partner typically sleep? - Other (please specify)',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us snores',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us makes frequent bathroom trips in the night',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us is sick',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - We are no longer physically intimate',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - We have different temperature preferences for the room',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - We've had an argument or fight',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - Not enough space',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - Do not want to share the covers',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us needs to sleep with a child',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - Night working/very different sleeping times',
       'What are the reasons that you sleep in separate beds? Please select all that apply. - Other (please specify)',
       'When was the first time you slept in separate beds? - Response',
       'To what extent do you agree with the following statement: "sleeping in separate beds helps us to stay together." - Response',
       'To what extent do you agree with the following statement: "we sleep better when we sleep in separate beds." - Response',
       'To what extent do you agree with the following statement:ë_"our sex life has improved as a result of sleeping in separate beds."ë_ - Response',
       'Which of the following best describes your current occupation? - Response',
       'Which of the following best describes your current occupation? - Other (please specify)'],
      dtype='object')

In [39]:
drop_list = ['StartDate', 'EndDate']
dataset_modified = dataset_modified.drop(columns=drop_list)
dataset_modified

,ID,Gender - Response,Age - Response,Household Income - Response,Education - Response,Location (Census Region) - Response,Which of the following best describes your current relationship status? - Response,"How long have you been in your current relationship? If you are not currently in a relationship, please answer according to your last relationship. - Response","When both you and your partner are at home, how often do you sleep in separate beds? - Response","When you're not sleeping in the same bed as your partner, where do you typically sleep? - Response",...,What are the reasons that you sleep in separate beds? Please select all that apply. - Do not want to share the covers,What are the reasons that you sleep in separate beds? Please select all that apply. - One of us needs to sleep with a child,What are the reasons that you sleep in separate beds? Please select all that apply. - Night working/very different sleeping times,What are the reasons that you sleep in separate beds? Please select all that apply. - Other (please specify),When was the first time you slept in separate beds? - Response,"To what extent do you agree with the following statement: ""sleeping in separate beds helps us to stay together."" - Response","To what extent do you agree with the following statement: ""we sleep better when we sleep in separate beds."" - Response","To what extent do you agree with the following statement:ë_""our sex life has improved as a result of sleeping in separate beds.""ë_ - Response",Which of the following best describes your current occupation? - Response,Which of the following best describes your current occupation? - Other (please specify)
0,1,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,"Single, but cohabiting with a significant other",1-5 years,Once a year or less,On the couch/chair,...,NaN,NaN,NaN,Other (please specify),Within the first 1-5 years of our relationship,Strongly disagree,Somewhat agree,Strongly disagree,Other (please specify),Student
1,2,Male,18-29,NaN,Bachelor degree,South Atlantic,"Single, but cohabiting with a significant other",1-5 years,A few times per month,"I sleep in our shared bed, my partner is the o...",...,Do not want to share the covers,NaN,NaN,NaN,Immediately/ We've always slept in separate beds,Somewhat agree,Strongly agree,Strongly disagree,Healthcare Support Occupations,NaN
2,3,Male,18-29,"$150,000+",Graduate degree,South Atlantic,Married,1-5 years,Never,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Legal Occupations,NaN
3,4,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,Married,1-5 years,Never,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Life, Physical, and Social Science Occupations",NaN
4,5,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,Married,1-5 years,Never,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,1089,Female,30-44,NaN,Bachelor degree,South Atlantic,Married,Less than 1 year,Once a year or less,"I sleep in our shared bed, my partner is the o...",...,NaN,NaN,Night working/very different sleeping times,NaN,Within the first 1-5 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,"Arts, Design, Entertainment, Sports, and Media...",NaN
1089,1090,Male,> 60,NaN,High school degree,East North Central,Married,More than 20 years,Every night,On the couch/chair,...,NaN,NaN,NaN,NaN,After 20 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Other (please specify),retired
1090,1091,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,Married,1-5 years,Never,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Management Occupations,NaN
1091,1092,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,Separated,16-20 years,Never,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Arts, Design, Entertainment, Sports, and Media...",NaN
1092,1093,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,Married,More than 20 years,Never,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,NaN

In [43]:
id_list = list(dataset_modified.columns[:6])
# id_list

['ID',
 'Gender - Response',
 'Age - Response',
 'Household Income - Response',
 'Education - Response',
 'Location (Census Region) - Response']

In [45]:
value_list = list(dataset_modified.columns[6:])
# value_list

['Which of the following best describes your current relationship status? - Response',
 'How long have you been in your current relationship? If you are not currently in a relationship, please answer according to your last relationship. - Response',
 'When both you and your partner are at home, how often do you sleep in separate beds? - Response',
 "When you're not sleeping in the same bed as your partner, where do you typically sleep? - Response",
 "When you're not sleeping in the same bed as your partner, where do you typically sleep? - Other (please specify)",
 "When you're not sleeping in the same bed, where does your partner typically sleep? - Response",
 "When you're not sleeping in the same bed, where does your partner typically sleep? - Other (please specify)",
 'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us snores',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us makes frequent bathroom trips in the night',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us is sick',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - We are no longer physically intimate',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - We have different temperature preferences for the room',
 "What are the reasons that you sleep in separate beds? Please select all that apply. - We've had an argument or fight",
 'What are the reasons that you sleep in separate beds? Please select all that apply. - Not enough space',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - Do not want to share the covers',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - One of us needs to sleep with a child',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - Night working/very different sleeping times',
 'What are the reasons that you sleep in separate beds? Please select all that apply. - Other (please specify)',
 'When was the first time you slept in separate beds? - Response',
 'To what extent do you agree with the following statement: "sleeping in separate beds helps us to stay together." - Response',
 'To what extent do you agree with the following statement: "we sleep better when we sleep in separate beds." - Response',
 'To what extent do you agree with the following statement:ë_"our sex life has improved as a result of sleeping in separate beds."ë_ - Response',
 'Which of the following best describes your current occupation? - Response',
 'Which of the following best describes your current occupation? - Other (please specify)']

In [47]:
dataset_melted = dataset_modified.melt(id_vars=id_list, value_vars=value_list, var_name="Question+Subquestion", value_name="Answer")
dataset_melted

,ID,Gender - Response,Age - Response,Household Income - Response,Education - Response,Location (Census Region) - Response,Question+Subquestion,Answer
0,1,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,Which of the following best describes your cur...,"Single, but cohabiting with a significant other"
1,2,Male,18-29,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,"Single, but cohabiting with a significant other"
2,3,Male,18-29,"$150,000+",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married
3,4,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,Married
4,5,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married
...,...,...,...,...,...,...,...,...
26227,1089,Female,30-44,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,NaN
26228,1090,Male,> 60,NaN,High school degree,East North Central,Which of the following best describes your cur...,retired
26229,1091,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,NaN
26230,1092,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,Which of the following best describes your cur...,NaN
26231,1093,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,Which of the following best describes your cur...,NaN

In [65]:
questions_import = pd.read_excel(pwd + "\\Data - Copy of Source.xlsx", sheet_name="Question")
questions_import = questions_import.rename(columns={"Question + Subquestion": "Question+Subquestion"})
questions_import

,Raw Question,Raw Subquestion,Question,Subquestion,Question+Subquestion
0,ID,NaN,ID,0,ID
1,StartDate,NaN,StartDate,0,StartDate
2,EndDate,NaN,EndDate,0,EndDate
3,Which of the following best describes your cur...,Response,Which of the following best describes your cur...,Response,Which of the following best describes your cur...
4,How long have you been in your current relatio...,Response,How long have you been in your current relatio...,Response,How long have you been in your current relatio...
5,"When both you and your partner are at home, ho...",Response,"When both you and your partner are at home, ho...",Response,"When both you and your partner are at home, ho..."
6,When you're not sleeping in the same bed as yo...,Response,When you're not sleeping in the same bed as yo...,Response,When you're not sleeping in the same bed as yo...
7,NaN,Other (please specify),When you're not sleeping in the same bed as yo...,Other (please specify),When you're not sleeping in the same bed as yo...
8,"When you're not sleeping in the same bed, wher...",Response,"When you're not sleeping in the same bed, wher...",Response,"When you're not sleeping in the same bed, wher..."
9,NaN,Other (please specify),"When you're not sleeping in the same bed, wher...",Other (please specify),"When you're not sleeping in the same bed, wher..."
10,What are the reasons that you sleep in separat...,One of us snores,What are the reasons that you sleep in separat...,One of us snores,What are the reasons that you sleep in separat...
11,NaN,One of us makes frequent bathroom trips in the...,What are the reasons that you sleep in separat...,One of us makes frequent bathroom trips in the...,What are the reasons that you sleep in separat...
12,NaN,One of us is sick,What are the reasons that you sleep in separat...,One of us is sick,What are the reasons that you sleep in separat...
13,NaN,We are no longer physically intimate,What are the reasons that you sleep in separat...,We are no longer physically intimate,What are the reasons that you sleep in separat...
14,NaN,We have different temperature preferences for ...,What are the reasons that you sleep in separat...,We have different temperature preferences for ...,What are the reasons that you sleep in separat...
15,NaN,We've had an argument or fight,What are the reasons that you sleep in separat...,We've had an argument or fight,What are the reasons that you sleep in separat...
16,NaN,Not enough space,What are the reasons that you sleep in separat...,Not enough space,What are the reasons that you sleep in separat...
17,NaN,Do not want to share the covers,What are the reasons that you sleep in separat...,Do not want to share the covers,What are the reasons that you sleep in separat...
18,NaN,One of us needs to sleep with a child,What are the reasons that you sleep in separat...,One of us needs to sleep with a child,What are the reasons that you sleep in separat...
19,NaN,Night working/very different sleeping times,What are the reasons that you sleep in separat...,Night working/very different sleeping times,What are the reasons that you sleep in separat...
20,NaN,Other (please specify),What are the reasons that you sleep in separat...,Other (please specify),What are the reasons that you sleep in separat...
21,When was the first time you slept in separate ...,Response,When was the first time you slept in separate ...,Response,When was the first time you slept in separate ...
22,To what extent do you agree with the following...,Response,To what extent do you agree with the following...,Response,To what extent do you agree with the following...
23,To what extent do you agree with the following...,Response,To what extent do you agree with the following...,Response,To what extent do you agree with the following...
24,To what extent do you agree with the following...,Response,To what extent do you agree with the following...,Response,To what extent do you agree with the following...
25,Which of the following best describes your cur...,Response,Which of the following best describes your cur...,Response,Which of the following best describes your cur...
26,NaN,Other (please specify),Which of the following best describes your cur...,Other (please specify),Which of the following best describes your cur...
27,Gender,Response,Gender,Response,Gender - Response
28,Age,Response,Age,Response,Age - Response
29,Household Income,Response,Household Income,Response,Household Income - Response
30,Education,Response,Education,Response,Education - Response
31,Location (Census Region),Response,Location (Census Region),Response,Location (Census Region) - Response

In [67]:
questions = questions_import.copy()
questions = questions.drop(columns=['Raw Question', 'Raw Subquestion', 'Subquestion'])
questions

,Question,Question+Subquestion
0,ID,ID
1,StartDate,StartDate
2,EndDate,EndDate
3,Which of the following best describes your cur...,Which of the following best describes your cur...
4,How long have you been in your current relatio...,How long have you been in your current relatio...
5,"When both you and your partner are at home, ho...","When both you and your partner are at home, ho..."
6,When you're not sleeping in the same bed as yo...,When you're not sleeping in the same bed as yo...
7,When you're not sleeping in the same bed as yo...,When you're not sleeping in the same bed as yo...
8,"When you're not sleeping in the same bed, wher...","When you're not sleeping in the same bed, wher..."
9,"When you're not sleeping in the same bed, wher...","When you're not sleeping in the same bed, wher..."
10,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
11,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
12,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
13,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
14,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
15,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
16,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
17,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
18,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
19,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
20,What are the reasons that you sleep in separat...,What are the reasons that you sleep in separat...
21,When was the first time you slept in separate ...,When was the first time you slept in separate ...
22,To what extent do you agree with the following...,To what extent do you agree with the following...
23,To what extent do you agree with the following...,To what extent do you agree with the following...
24,To what extent do you agree with the following...,To what extent do you agree with the following...
25,Which of the following best describes your cur...,Which of the following best describes your cur...
26,Which of the following best describes your cur...,Which of the following best describes your cur...
27,Gender,Gender - Response
28,Age,Age - Response
29,Household Income,Household Income - Response
30,Education,Education - Response
31,Location (Census Region),Location (Census Region) - Response

In [69]:
dataset_merged = pd.merge(left=dataset_melted, right=questions, how="left", left_on="Question+Subquestion", right_on="Question+Subquestion")

In [70]:
dataset_merged

,ID,Gender - Response,Age - Response,Household Income - Response,Education - Response,Location (Census Region) - Response,Question+Subquestion,Answer,Question
0,1,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,Which of the following best describes your cur...,"Single, but cohabiting with a significant other",Which of the following best describes your cur...
1,2,Male,18-29,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,"Single, but cohabiting with a significant other",Which of the following best describes your cur...
2,3,Male,18-29,"$150,000+",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...
3,4,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...
4,5,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...
...,...,...,...,...,...,...,...,...,...
26227,1089,Female,30-44,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...
26228,1090,Male,> 60,NaN,High school degree,East North Central,Which of the following best describes your cur...,retired,Which of the following best describes your cur...
26229,1091,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...
26230,1092,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...
26231,1093,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...

In [82]:
respondents = dataset_merged[dataset_merged['Answer'].notna()]
respondents = respondents.groupby('Question')['ID'].nunique().reset_index()
respondents = respondents.rename(columns={"ID": "Respondents"})
respondents

                                             Question  Respondents
0   How long have you been in your current relatio...         1079
1   To what extent do you agree with the following...          481
2   To what extent do you agree with the following...          481
3   To what extent do you agree with the following...          481
4   What are the reasons that you sleep in separat...          482
5   When both you and your partner are at home, ho...         1079
6   When was the first time you slept in separate ...          482
7   When you're not sleeping in the same bed as yo...          482
8   When you're not sleeping in the same bed, wher...          482
9   Which of the following best describes your cur...         1064
10  Which of the following best describes your cur...         1093

In [85]:
dataset_merged_two = pd.merge(left=dataset_merged, right=respondents, how="left", left_on="Question", right_on="Question")
dataset_merged_two

,ID,Gender - Response,Age - Response,Household Income - Response,Education - Response,Location (Census Region) - Response,Question+Subquestion,Answer,Question,Respondents
0,1,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,Which of the following best describes your cur...,"Single, but cohabiting with a significant other",Which of the following best describes your cur...,1093
1,2,Male,18-29,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,"Single, but cohabiting with a significant other",Which of the following best describes your cur...,1093
2,3,Male,18-29,"$150,000+",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...,1093
3,4,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...,1093
4,5,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...,1093
...,...,...,...,...,...,...,...,...,...,...
26227,1089,Female,30-44,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064
26228,1090,Male,> 60,NaN,High school degree,East North Central,Which of the following best describes your cur...,retired,Which of the following best describes your cur...,1064
26229,1091,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064
26230,1092,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064
26231,1093,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064

In [89]:
same_answer = dataset_merged # [dataset_merged['Answer'].notna()]
same_answer = same_answer.groupby(['Question+Subquestion', 'Answer'])['ID'].nunique().reset_index()
same_answer = same_answer.rename(columns={"ID": "Same Answer"})
same_answer

,Question+Subquestion,Answer,Same Answer
0,How long have you been in your current relatio...,1-5 years,162
1,How long have you been in your current relatio...,11-15 years,159
2,How long have you been in your current relatio...,16-20 years,104
3,How long have you been in your current relatio...,6-10 years,165
4,How long have you been in your current relatio...,Less than 1 year,21
...,...,...,...
275,Which of the following best describes your cur...,In a domestic partnership or civil union,48
276,Which of the following best describes your cur...,Married,884
277,Which of the following best describes your cur...,Separated,8
278,Which of the following best describes your cur...,"Single, but cohabiting with a significant other",138
279,Which of the following best describes your cur...,Widowed,3

In [101]:
dataset_merged_three = pd.merge(left=dataset_merged_two, right=same_answer, how="left", left_on=['Question+Subquestion', "Answer"], right_on=['Question+Subquestion', "Answer"])
dataset_merged_three = dataset_merged_three.fillna(value = {"Same Answer": 0})
dataset_merged_three

,ID,Gender - Response,Age - Response,Household Income - Response,Education - Response,Location (Census Region) - Response,Question+Subquestion,Answer,Question,Respondents,Same Answer
0,1,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,Which of the following best describes your cur...,"Single, but cohabiting with a significant other",Which of the following best describes your cur...,1093,138.0
1,2,Male,18-29,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,"Single, but cohabiting with a significant other",Which of the following best describes your cur...,1093,138.0
2,3,Male,18-29,"$150,000+",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...,1093,884.0
3,4,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...,1093,884.0
4,5,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,Which of the following best describes your cur...,Married,Which of the following best describes your cur...,1093,884.0
...,...,...,...,...,...,...,...,...,...,...,...
26227,1089,Female,30-44,NaN,Bachelor degree,South Atlantic,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064,0.0
26228,1090,Male,> 60,NaN,High school degree,East North Central,Which of the following best describes your cur...,retired,Which of the following best describes your cur...,1064,72.0
26229,1091,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064,0.0
26230,1092,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064,0.0
26231,1093,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,Which of the following best describes your cur...,NaN,Which of the following best describes your cur...,1064,0.0

In [102]:
output = dataset_merged_three.copy()
output.to_excel(pwd + "\\Data - Final Output.xlsx", index=False)